# Generated by Django 3.2.23 on 2024-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisosRecomendaciones',
            fields=[
                ('id_AyR', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_avisos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConoceNumerosEmergencia',
            fields=[
                ('id_CNEmergencia', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_cne', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConoceServiciosEmergencia',
            fields=[
                ('id_CSEmergencia', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_cse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_ResPersona', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_cse', models.CharField(max_length=255)),
                ('opcion_cne', models.CharField(max_length=255)),
                ('opcion_uso911', models.CharField(max_length=255)),
                ('opcion_rapidez', models.IntegerField()),
                ('opcion_usarapp', models.CharField(max_length=255)),
                ('opcion_avisos', models.CharField(max_length=255)),
                ('opcion_mapa', models.CharField(max_length=255)),
                ('opcion_paleta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MapaInteractivo',
            fields=[
                ('id_MapaInteractivo', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_mapa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaletaColores',
            fields=[
                ('id_PColores', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_paleta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RapidezServicio',
            fields=[
                ('id_RServicio', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_rapidez', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupUsuario',
            fields=[
                ('idSupUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSupUsuario', models.CharField(db_column='nombre_SupUsuario', max_length=100)),
                ('correoSupUsuario', models.CharField(db_column='correo_SupUsuario', max_length=100)),
                ('contraSupUsuario', models.CharField(db_column='contra_SupUsuario', max_length=100)),
            ],
            options={
                'db_table': 'SuperUsuarioTabla',
            },
        ),
        migrations.CreateModel(
            name='UsarAppEmergencia',
            fields=[
                ('id_UApp', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_usarapp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uso911',
            fields=[
                ('id_Uso911', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_uso911', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(db_column='nombre_Usuario', max_length=100)),
                ('correoUsuario', models.CharField(db_column='correo_Usuario', max_length=100, unique=True)),
                ('contraUsuario', models.CharField(db_column='contra_Usuario', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'UsuarioTabla',
            },
        ),
    ]
