# Generated by Django 3.2.23 on 2024-01-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_recuperacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correoUsuario',
            field=models.CharField(db_column='correo_Usuario', max_length=100),
        ),
    ]
